apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: One Time Password SMS
  version: 1.1.0
operations:
  POST /send-code:
    Valid-Request1:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "phoneNumber" : "+123456789",
            "message" : "Your OTP code is {{code}}"
          }
      response:
        headers:
          content-type: application/json
        status: 200
        mediaType: application/json
        body: |-
          {
            "authenticationId" : "123e4567-e89b-12d3-a456-426614174000"
          }
    Invalid-Request2:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "phoneNumber" : "123456789",
            "message" : "Your OTP code is {{code}}"
          }
      response:
        headers:
          content-type: application/json
        status: 400
        mediaType: application/json
        body: |-
          {
            "status" : 400,
            "code" : "INVALID_ARGUMENT",
            "message" : "Phone number is invalid. It should be in international format starting with '+'"
          }
    Rate-Limited-Request:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "phoneNumber" : "+987654321",
            "message" : "Your OTP code is {{code}}"
          }
      response:
        headers:
          content-type: application/json
        status: 429
        mediaType: application/json
        body: |-
          {
            "status" : 429,
            "code" : "TOO_MANY_REQUESTS",
            "message" : "You have reached the rate limiting limit for sending OTP codes."
          }
    Send OTP code to a phone number:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "phoneNumber" : "+1234567890",
            "message" : "Your OTP code is: {{code}}. Please use it to verify your number."
          }
      response:
        headers:
          content-type: application/json
        status: 200
        mediaType: application/json
        body: |-
          {
            "authenticationId" : "10101010-2020-3030-4040-505050505050"
          }
    Fail to send OTP code with invalid phone number:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "phoneNumber" : "1234567890",
            "message" : "Your OTP code is: {{code}}."
          }
      response:
        headers:
          content-type: application/json
        status: 400
        mediaType: application/json
        body: |-
          {
            "status" : 400,
            "code" : "INVALID_ARGUMENT",
            "message" : "Phone number is not in the correct format. Please provide a number in international format starting with a plus sign."
          }
    Fail to send OTP code due to quota exceeded:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "phoneNumber" : "+9876543210",
            "message" : "Your code is: {{code}}"
          }
      response:
        headers:
          content-type: application/json
        status: 429
        mediaType: application/json
        body: |-
          {
            "status" : 429,
            "code" : "QUOTA_EXCEEDED",
            "message" : "API request quota exceeded. Please try again later."
          }
  POST /validate-code:
    Valid code validation:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "authenticationId" : "7ba2eb62-1c4a-46f2-bb4c-21bcac10b03a",
            "code" : "123456"
          }
      response:
        headers:
          content-type: application/json
        status: 204
        mediaType: application/json
    Expired AuthenticationId:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "authenticationId" : "ecf9047e-e6e4-4e58-b908-158c314946a9",
            "code" : "654321"
          }
      response:
        headers:
          content-type: application/json
        status: 400
        mediaType: application/json
        body: |-
          {
            "status" : 400,
            "code" : "ONE_TIME_PASSWORD_SMS.VERIFICATION_EXPIRED",
            "message" : "The authenticationId is no longer valid"
          }
    Invalid OTP for AuthenticationId:
      request:
        headers:
          accept: application/json
        body: |-
          {
            "authenticationId" : "4f94c823-2eb1-4658-993d-ba6f8ab7527d",
            "code" : "999999"
          }
      response:
        headers:
          content-type: application/json
        status: 400
        mediaType: application/json
        body: |-
          {
            "status" : 400,
            "code" : "ONE_TIME_PASSWORD_SMS.INVALID_OTP",
            "message" : "The provided OTP is not valid for this authenticationId"
          }
    Valid OTP verification:
      request:
        headers:
          x-correlator: abc123
          accept: application/json
        body: |-
          {
            "authenticationId" : "54b10c56-0d46-48c2-b6f4-048afe18f592",
            "code" : "123456"
          }
      response:
        headers:
          content-type: application/json
        status: 204
        mediaType: application/json
    Invalid OTP verification - Max attempts exceeded:
      request:
        headers:
          x-correlator: def456
          accept: application/json
        body: |-
          {
            "authenticationId" : "b9fb7ce0-164e-4c37-802b-54d86db1e9c5",
            "code" : "654321"
          }
      response:
        headers:
          content-type: application/json
        status: 400
        mediaType: application/json
        body: |-
          {
            "status" : 400,
            "code" : "ONE_TIME_PASSWORD_SMS.VERIFICATION_FAILED",
            "message" : "The maximum number of attempts for this authenticationId was exceeded without providing a valid OTP"
          }
    Expired OTP verification:
      request:
        headers:
          x-correlator: xyz789
          accept: application/json
        body: |-
          {
            "authenticationId" : "c36e9ca1-2362-46e2-b6b5-275127e5d183",
            "code" : "987654"
          }
      response:
        headers:
          content-type: application/json
        status: 400
        mediaType: application/json
        body: |-
          {
            "status" : 400,
            "code" : "ONE_TIME_PASSWORD_SMS.VERIFICATION_EXPIRED",
            "message" : "The authenticationId is no longer valid"
          }
